// common
export const LOAD_STATE = 'LOAD_STATE'
export const LOAD_SUBFILE = 'LOAD_SUBFILE'

// ui
export const SET_LEFT_PANEL_WIDTH = 'SET_LEFT_PANEL_WIDTH'
export const SET_CENTRAL_PANEL_WIDTH = 'SET_CENTRAL_PANEL_WIDTH'
export const SET_VIDEO_VIEW_HEIGHT = 'SET_VIDEO_VIEW_HEIGHT'
export const SET_PROJECT_SORT_ORDER = 'SET_PROJECT_SORT_ORDER'

// subfiles
export const ADD_PROJECT = 'ADD_PROJECT'
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const CHANGE_PROJECT_PROPERTIES = 'CHANGE_PROJECT_PROPERTIES'
export const CHANGE_PROJECT_EXPORT_NAME = 'CHANGE_PROJECT_EXPORT_NAME'
export const CHANGE_PROJECT_EXPORT_PATH = 'CHANGE_PROJECT_EXPORT_PATH'
export const SET_SUBFILE_FILTER = 'SET_SUBFILE_FILTER'
export const ADD_SUBTITLE = 'ADD_SUBTITLE'
export const SET_TRANSLATED_SUBTITLES_COUNT = 'SET_TRANSLATED_SUBTITLES_COUNT'
export const ADD_SUBTITLES = 'ADD_SUBTITLES'
export const CLEAR_SUBTITLES = 'CLEAR_SUBTITLES'
export const MAKE_SUBTITLE_ACTIVE = 'MAKE_SUBTITLE_ACTIVE'
export const UPDATE_SUBTITLE = 'UPDATE_SUBTITLE'
export const UPDATE_SUBTITLE_FULL = 'UPDATE_SUBTITLE_FULL'
export const INSERT_SUBTITLE = 'INSERT_SUBTITLE'
export const DELETE_SUBTITLE = 'DELETE_SUBTITLE'
export const RENUMBER_SUBTITLE = 'RENUMBER_SUBTITLE'
export const SET_SUBTITLE_TIME = 'SET_SUBTITLE_TIME'
export const SET_DEFAULT_EXPORT_PATH = 'SET_DEFAULT_EXPORT_PATH'
export const SET_DEFAULT_LANGUAGE = 'SET_DEFAULT_LANGUAGE'
export const SET_VIDEO_FILE = 'SET_VIDEO_FILE'
export const SET_CURRENT_VIDEO_POSITION = 'SET_CURRENT_VIDEO_POSITION'
export const CLEAR_VIDEO_FILE = 'CLEAR_VIDEO_FILE'

// player
// export const SET_CANVAS = 'SET_CANVAS'
export const PLUGINS_EXIST = 'PLUGINS_EXIST'
export const MUTE_PLAYER = 'MUTE_PLAYER'
export const SET_VOLUME = 'SET_VOLUME'
export const SET_VIDEO_METADATA = 'SET_VIDEO_METADATA'
export const SET_SUBFILE = 'SET_SUBFILE'
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME'
export const SET_CURRENT_POSITION = 'SET_CURRENT_POSITION'
export const SET_BUFFERING = 'SET_BUFFERING'
export const SET_PLAYER_STATE = 'SET_PLAYER_STATE'
export const RESET_VIDEO = 'RESET_VIDEO'
export const STOP_AFTER_PLAY = 'STOP_AFTER_PLAY'


// opensubtitles
export const SET_OST_CREDENTIALS = 'SET_OST_CREDENTIALS'
export const SET_OST_SSL = 'SET_OST_SSL'
export const SET_OST_VERIFIED = 'SET_OST_VERIFIED'
